name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            cuda_major_version: ['11']
            cuda_minor_version: ['7', '8']
            cuda_patch_version: ['0']


    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build the Docker image
      env:
          PUSH_COMMAND: ${{ github.ref =='refs/heads/main' && '--push' || '' }}
      run: |
        bash ./build.sh -d --image-name ${{ secrets.DOCKERHUB_ORG }}/cudagl --cuda-version ${{ matrix.cuda_major_version }}.${{ matrix.cuda_minor_version}}.${{ matrix.cuda_patch_version }} --os ubuntu --os-version 20.04 --arch x86_64 --cudagl ${{ env. PUSH_COMMAND }}

